apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: goserver
  newName: jongcarvalho/gitopsfc
  newTag: 4f8df81498265ad82209dd58f60018629e5e3f61
