- name: Checkout code
  uses: actions/checkout@v2

- name: Login to Docker Hub
  uses: docker/login-action@v3 # Use a versão mais recente, por exemplo v3
  with:
    username: ${{ secrets.DOCKER_USERNAME }}
    password: ${{ secrets.DOCKER_PASSWORD }}

- name: Build and push image to Dockerhub
  uses: docker/build-push-action@v5 # Altere para a versão mais recente
  with:
    context: . # Adicione o contexto se seu Dockerfile estiver na raiz
    push: true # Explicitamente diga para fazer o push
    tags: ${{ secrets.DOCKER_USERNAME }}/gitopsfc:${{ github.sha }}, ${{ secrets.DOCKER_USERNAME }}/gitopsfc:latest